#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawLimit,      sensorPotentiometer)
#pragma config(Sensor, in2,    lineRIGHT,      sensorReflection)
#pragma config(Sensor, in3,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in4,    lineLEFT,       sensorReflection)
#pragma config(Sensor, in5,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in6,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  LIMITSWITCHRIGHT, sensorTouch)
#pragma config(Sensor, dgtl9,  LIMITSWITCHLEFT, sensorTouch)
#pragma config(Sensor, dgtl10, Bumper,         sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393HighSpeed_HBridge, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port2,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393HighSpeed_HBridge, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



//BB-UART Serial Information
#define PORT "/dev/ttyO4"
#define BAUDRATE B115200



struct Data
{
	short SonarValue;
	short ArmValue;
	bool Drive;
	bool ArmDown;
	bool ClawClosed;
	int Batt;
};
int MOTORPOWER = 35;
int CLAWPOWER = 45; //claw electrical power
int ARMPOWER = 35; //arm electrical power
bool frontFlag = false;
bool armUp =false;
bool clawOpen =false;
bool isTurning = false;
char rcvInput  = '0';

Data TxPkt;

void openClaw(){
		wait1Msec(500);
		motor[clawMotor] = CLAWPOWER;
		wait1Msec(650);
		motor[clawMotor] = 0;
	}
	//Close claw and stop motor
void closeClaw(){
		motor[clawMotor] = -CLAWPOWER;
		wait1Msec(600);
		motor[clawMotor] = 0;
}

void liftArm(int d){
		while (SensorValue[clawLimit] > d){ // claw limit exceeded - dont do anything
			motor[armMotor] = -ARMPOWER - 10;
		}
		motor[armMotor] = 0;
		wait1Msec(250);
	}

	//Lower arm until it reaches the bottom
	void lowerArm(){
		int tempPos = 0;
		while (SensorValue[clawLimit] < 4050){
			tempPos = SensorValue[clawLimit];
			motor[armMotor] = ARMPOWER;
			wait1Msec(200);
		}
		motor[armMotor] = 0;
		wait1Msec(500);
	}
task frontCheck(){


	while(true){
		int sensorCheck = SensorValue[sonarSensor];
		if(sensorCheck > -1 && sensorCheck <= 15){
			frontFlag = true;
			//stopAllMotors();
		}
		else{
			frontFlag = false;
		}
		wait1Msec(2000);
		continue;
	}

}

task UARTRx() {
	//Receiving Data
	char rcvChar;		//Variable to hold the reciving byte data

	while (true)
	{
		rcvChar = getChar(uartOne);
		rcvInput = rcvChar;
		wait1Msec(3);
	 	continue;

	/*	if(rcvChar == '1' && TxPkt.Drive == false)
		{
			TxPkt.Drive = true;
			motor[leftMotor] = 35;
			motor[rightMotor] = 35;
		} else if (rcvChar == '1' && TxPkt.Drive == true) {
				TxPkt.Drive = false;
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}*/
	}
}


task main()
{
	TxPkt.SonarValue = TxPkt.ArmValue = 0;
	TxPkt.Drive = false;
	TxPkt.ArmDown = true;
	TxPkt.ClawClosed = true;
	TxPkt.Batt = 100;
	startTask(UARTRx);
	startTask(frontCheck);
//Sending Data

		char *ptr = (char *)&TxPkt;
while(true) {

			switch(rcvInput){
				case '1' :
						if(frontFlag == false){
							stopAllMotors();
      				isTurning = false;
      				if (TxPkt.Drive == true) {
								stopAllMotors();
								TxPkt.Drive = false;
							}else if (TxPkt.Drive == false) {
								motor[leftMotor] = MOTORPOWER;
								motor[rightMotor] = MOTORPOWER;
								TxPkt.Drive = true;
							}
							rcvInput ='0';
							break;
					}
					else{
						stopAllMotors();
         		TxPkt.Drive = false;
         		rcvInput ='0';
         		break;
				}
      /*	case '2' :
      			stopAllMotors();
      			isTurning = false;
      			if (TxPkt.Drive == true) {
							stopAllMotors();
							TxPkt.Drive = false;
						}else if (TxPkt.Drive == false) {
							motor[leftMotor] = -MOTORPOWER;
							motor[rightMotor] = -MOTORPOWER;
							TxPkt.Drive = true;
						}
						rcvInput ='0';
						break;
      	case '3' :
         		stopAllMotors();
         		TxPkt.Drive = false;

         		if(isTurning == false){
         			motor[rightMotor] = MOTORPOWER;
         			isTurning = true;
         		}else if(isTurning == true){
         			stopAllMotors();
         			isTurning = false;
         		}
         		rcvInput ='0';
         	break;
      	case '4' :
         		stopAllMotors();
         		TxPkt.Drive = false;
         		if(isTurning == false){
         			motor[leftMotor] = MOTORPOWER;
         			isTurning = true;
         		}else if(isTurning == true){
         			stopAllMotors();
         			isTurning = false;
         		}
         		rcvInput ='0';
         	break;

         	case '5' :
         		stopAllMotors();
         		isTurning = false;
         		TxPkt.Drive = false;

         		if(armUp == false){
         			liftArm(3900);
         			armUp = true;
         		}else if(armUp == true){
         			lowerArm();
         			armUp = false;
         		}
         		rcvInput ='0';
         	break;

         	case '6' :
         		stopAllMotors();
         		isTurning = false;
         		TxPkt.Drive = false;
         		if(clawOpen == false){
         			openClaw();
         			clawOpen = true;
         		}else if(clawOpen == true){
         			closeClaw();
         			clawOpen = false;
         		}
         		rcvInput ='0';
         	break;
         	*/
      	default :
         	stopAllMotors();
			}
		}
}
