#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawLimit,      sensorPotentiometer)
#pragma config(Sensor, in2,    lineRIGHT,      sensorReflection)
#pragma config(Sensor, in3,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in4,    lineLEFT,       sensorReflection)
#pragma config(Sensor, in5,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in6,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  LIMITSWITCHRIGHT, sensorTouch)
#pragma config(Sensor, dgtl9,  LIMITSWITCHLEFT, sensorTouch)
#pragma config(Sensor, dgtl10, Bumper,         sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393HighSpeed_HBridge, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port2,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393HighSpeed_HBridge, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(UART_Usage, UART2, uartOne, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int CLAWPOWER = 40;
	void closeClaw(){
		motor[clawMotor] = -CLAWPOWER;
		wait1Msec(600);
		motor[clawMotor] = 0;
	}
		void openClaw(){
		motor[clawMotor] = CLAWPOWER;
		wait1Msec(650);
		motor[clawMotor] = 0;
	}
	void doNothing(){}
task main() {

  while(true) {
	    sendChar(uartOne, 'A');
	    delay(250);
	    	    sendChar(uartOne, 'B');
	    delay(250);
	    	    sendChar(uartOne, 'C');
	    delay(250);
	    
	   char INPUT = getChar(uartOne); 
	    switch(INPUT){
	    	case 'A':
	    	openClaw();
	    	break;
	    	case 'B':
	    	closeClaw();
	    	break;
	    	default:
	    	doNothing();
	    	break;
	  }

	}

}
