#pragma config(CircuitBoardType, typeCktBoardUNO)
#pragma config(Motor,  servo_A,         rightMotor,    tmotorServoContinuousRotation, openLoop, IOPins, dgt5, None)
#pragma config(Motor,  servo_B,         leftMotor,     tmotorServoContinuousRotation, openLoop, IOPins, dgt6, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int bursts = 0;                         // Create variable 'bursts' of type int and set it to '0'.

do
{
  motor[rightMotor] = 100;  // run 'rightMotor' at power level 50
  motor[leftMotor]  = 100;  // run 'leftMotor' at power level 50

  bursts = bursts + 1;     // increment 'bursts' by 1

  wait1Msec(3000);         // wait for 3000 milliseconds before continuing

}while(bursts < 3)   ;      // while 'bursts' is less than 3:

motor[rightMotor] = 0;  // stop 'rightMotor'
motor[leftMotor]  = 0;  // stop 'leftMotor'
}
