#pragma config(CircuitBoardType, typeCktBoardUNO)
#pragma config(Motor,  motor_5,          ,             tmotorExternalHBridgeSinglePWM, openLoop, IOPins, dgtl5, dgtl3)
#pragma config(Motor,  motor_6,          ,             tmotorExternalHBridgeSinglePWM, openLoop, IOPins, dgtl6, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {
    motor[motor_5] = 127;
    motor[motor_6] = 127;
    wait1Msec(2000);

    motor[motor_5] = 0;
    motor[motor_6] = 0;
    wait1Msec(2000);

    motor[motor_5] = -127;
    motor[motor_6] = -127;
    wait1Msec(2000);

    motor[motor_5] = 0;
    motor[motor_6] = 0;
    wait1Msec(2000);
  }
}
